# ##setwd("X:/Claire/Lobster")
# library(DT)
# library(shiny)
# library(leaflet)
# library(RColorBrewer)
# library(scales)
# library(lattice)
# library(dplyr)
# library(devtools)
# library(grDevices)
# library(raster)
# library(wesanderson)
# library(rgdal)
# 
# lobs <- readOGR(dsn="LobsterManagementAreas.shp",layer = "LobsterManagementAreas")
# # ecoLines84<-spTransform(ecoLines, CRS("+init=epsg:4326"))

##setwd("X:/Claire/Lobster")
##setwd("K:/Lobster-master/Lobster-master")
#library(rsconnect)
#library(DT)
library(devtools)
library(shiny)
library(leaflet)
#library(RColorBrewer)
#library(scales)
#library(lattice)
#library(dplyr)

#library(grDevices)
#library(raster)
#library(wesanderson)
library(rgdal)

lobs <- readOGR(dsn="LobsterManagementAreas.shp",layer = "LobsterManagementAreas")
# ecoLines84<-spTransform(ecoLines, CRS("+init=epsg:4326"))
