##setwd("X:/Claire/Lobster")
library(DT)
library(shiny)
library(leaflet)
library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)
library(devtools)
library(grDevices)
library(raster)
library(wesanderson)
library(rgdal)

lobs <- readOGR(dsn="LobsterManagementAreas.shp",layer = "LobsterManagementAreas")
# ecoLines84<-spTransform(ecoLines, CRS("+init=epsg:4326"))